### ISSUE TITLE
登录时的虫子

### ISSUE THREAD

**Issue by Likxz** [vikiboss/ncu-auto-login-script#1]
老哥你的登录脚本在第50行后没有定义登录的账号类型。会导致提示找不到符合条件的产品。
在
49.userInput.value = config.username;
50.passInput.value = pwd;
后增加一行
domainSelect.value = config.type;
即可解决问题。没学过编程，观察到前面又定义type，但是后面没有进行选择，一葫芦画瓢添加一行，即可解决问题。
老哥的脚本好用，光速登录！

**Comment by vikiboss** [comment]
虽然我在今年 6 月份已经毕业用不到了，但还是感谢你的反馈，晚点有空就改改。

**Comment by vikiboss** [comment]
已更新

**Comment by vikiboss** [comment]
我自己没发现这个 bug 的主要原因，是因为我用的南昌大学家园工作室（ncuhome）发的教职工账号，不需要填 type（逃

**Comment by Likxz** [comment]
老哥，写错了，是domainSelect.value = config.type，你没注意写成passInput.value辣
哇，老哥厉害的，能进家园工作室很强的！我也23毕业的，去年没发挥好，回学校二战了

**Comment by vikiboss** [comment]
没测试（

**Comment by vikiboss** [comment]
好的（

**Comment by vikiboss** [comment]
好了，这下应该可以了，如果有帮助，欢迎分享给需要的同学～

**Comment by Likxz** [comment]
功能正常辣！芜湖~

**Comment by vikiboss** [comment]
二战加油

**Comment by Likxz** [comment]
谢谢老哥的祝福！冲冲冲！
