### ISSUE TITLE
this is so cool!

### ISSUE THREAD

**Issue by AGOMI7465** [vikiboss/ncu-auto-login-script#2]
感谢学长，现在连校园网老方便了，就是有没有手机端的呀?❤️😍

**Comment by vikiboss** [comment]
😂 当初也是偷懒，也很简单，就十几行核心代码。 

手机的话，我是 iOS，用的 Alook 浏览器，支持自定义脚本，然后我直接导入的这个脚本一样打开就自动登录。

如果你是安卓或许需要自己找一个支持自定义脚本的浏览器或者插件。

![image](https://github.com/user-attachments/assets/f1b297d6-7452-4c8f-890d-e158dde10a09)

**Comment by vikiboss** [comment]
> 感谢学长，现在连校园网老方便了，就是有没有手机端的呀?❤️😍

感谢认可 ❤️

**Comment by AGOMI7465** [comment]
wow~ ⊙o⊙我也下了个Alook照抄，一丝不差完美运行，恨不得给你多点几个star哈哈哈

**Comment by vikiboss** [comment]
过誉了 😂，兴趣驱动，真的非常简单，但是对我自己来说，确实非常实用。

如果你也对代码之类的东西感兴趣，也可以尝试着去了解了解 HTML、CSS、JavaScript，还是非常有意思的。
